name: EKS Deploy

permissions: {}

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

env:
  EKS_CLUSTER_NAME: wisecow-demo
  AWS_REGION: ap-south-1

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0' # default is latest stable
      id: install
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: |
        kubectl apply -f ./manifest/deployment.yaml
        kubectl apply -f ./manifest/service.yaml